version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_DATABASE_HOST: ${DB_HOST}
      APP_DATABASE: ${DB_PRODUCT}
      APP_DATABASE_USER: ${DB_USERNAME}
      APP_DATABASE_PASSWORD: ${DB_PASSWORD}


    #    depends_on:
    #      - db
    tty: true
    volumes:
      - .:/eiyorecipe # ソースコード変更したらDocker側も即反映されるように
      - websocket:/eiyorecipe/tmp/sockets/ # webのソケットを名前付きボリュームで同期必要なんじゃないかと思い作成


  #  db:
  #    build:
  #      context: ./docker/mysql
  #      dockerfile: Dockerfile
  #    environment:
  #      MYSQL_ROOT_PASSWORD: root
  #    ports:
  #      - "3306:3306" # ホストからゲストへポートフォワード
  #    volumes:
  #      - ./mysql_data:/var/lib/mysql

  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile

    ports:

      - 80:80
    volumes:
      - ./nginx/log:/var/log/nginx
      - websocket:/app/tmp/sockets/ # webのソケットを名前付きボリュームで同期必要なんじゃないかと思い作成
    depends_on:
      - app
volumes:
  websocket: # 共通ボリュームを作成

