version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_DATABASE_HOST: db
      APP_DATABASE: app_development
      APP_DATABASE_USER: root
      APP_DATABASE_PASSWORD: root
    depends_on:
      - db
    tty: true
    volumes:
      - .:/eiyorecipe # ソースコード変更したらDocker側も即反映されるように

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306" # ホストからゲストへポートフォワード
    volumes:
      - ./mysql_data:/var/lib/mysql


  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/log:/var/log/nginx
    volumes_from:
      - app
    depends_on:
      - app

